image: node:10.22.0

include:
  - template: Code-Quality.gitlab-ci.yml

stages: 
  - lint
  - test
  - quality
  - build

variables:
  GIT_SUBMODULE_STRATEGY: recursive

# Cache modules in between jobs
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm/


run_lint:
  stage: lint
  before_script:
    - npm ci --cache .npm --prefer-offline
  script:
    - npm run lint

run_test:
  stage: test
  script:
    - npm ci --cache .npm --prefer-offline
    - npm run test:coverage

run_build:
  stage: build
  before_script:
    - npm ci --cache .npm --prefer-offline
  script:
    - npm run package