image: node:10.22.0
include:
  - template: Code-Quality.gitlab-ci.yml

stages: 
  - lint
  - test
  - quality
  - build

# Cache modules in between jobs
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm/

before_script:
  - npm ci --cache .npm --prefer-offline

run_lint:
  stage: lint
  script:
    - npm run lint

run_test:
  stage: test
  script:
    - npm run test:coverage

run_build:
  stage: build
  script:
    - npm run package